USE contact_db;

CREATE TABLE IF NOT EXISTS leads (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  service VARCHAR(100) NOT NULL,
  budget VARCHAR(50),
  message TEXT,
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS feedback (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  product VARCHAR(100) NOT NULL,
  satisfaction INT(1) NOT NULL,
  suggestions TEXT,
  message TEXT,
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
);


CREATE TABLE IF NOT EXISTS leads (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, service VARCHAR(100) NOT NULL, budget VARCHAR(50), message TEXT, reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS feedback (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, product VARCHAR(100) NOT NULL, satisfaction INT(1) NOT NULL, suggestions TEXT, message TEXT, reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);